=== Soufiane-Chajjaoui/XMLProject/SCHEMA-ESTS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 

    <xs:element name="Universite" >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Etablissments">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Etablissment" maxOccurs="unbounded" type="TypeEtablissment" ></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="idUniversite" type="xs:ID" use="required"></xs:attribute>
            <xs:attribute name="UniversiteName" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>        
    </xs:element>
    <xs:complexType name="TypeEtablissment">
        <xs:all>
            <xs:element name="Departments" type="TypeDepartements"></xs:element>
            <xs:element name="Enseignants">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Enseignant" maxOccurs="unbounded" type="TypeEnseignant" minOccurs="1"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Etudiants">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Etudiant" maxOccurs="unbounded" type="Etudiant"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="idEtablissment" type="xs:ID" use="required"></xs:attribute>
        <xs:attribute name="NomEtablissment" type="xs:string" use="required"></xs:attribute>
        <xs:attribute name="VileEtablissment" type="xs:string" use="required"></xs:attribute>
        <xs:attribute name="RefUniversite" type="xs:IDREF" use="required"></xs:attribute>
    </xs:complexType>    
    <xs:complexType name="TypeDepartements">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="Department" >
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="idDepartment" use="required"></xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Person">
        <xs:sequence>
            <xs:element name="Prenom" type="xs:string"></xs:element>
            <xs:element name="Nom" type="xs:string"></xs:element>
            <xs:element name="Telephone">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <!--<xs:pattern value="^(06|07)\d{8}$"/>-->
                        <xs:length value="10"></xs:length>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"></xs:pattern>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="address" type="xs:string"></xs:element>
            <xs:element name="sex">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Homme"></xs:enumeration>
                        <xs:enumeration value="Femme"></xs:enumeration>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="DateNaissance" type="xs:date"></xs:element>
        </xs:sequence>
        <xs:attribute name="idPerson" type="xs:ID" use="required"></xs:attribute>
        <xs:attribute name="RefEtablissment" type="xs:IDREF"></xs:attribute>
    </xs:complexType>
    <xs:complexType name="Etudiant">
        <xs:complexContent>
            <xs:extension base="Person">
                <xs:sequence>
                    <xs:element name="Bac">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="SpecBac">
                                    <xs:simpleType>                                       
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="BAC SCIENCES MATHÉMATIQUES B."></xs:enumeration>
                                            <xs:enumeration value="BAC SCIENCES ÉCONOMIQUES."></xs:enumeration>
                                            <xs:enumeration value="BAC SCIENCES PHYSIQUES."></xs:enumeration>
                                            <xs:enumeration value="BAC SVT."></xs:enumeration>
                                            <xs:enumeration value="BAC SCIENCES MATHÉMATIQUES A."></xs:enumeration>
                                         </xs:restriction>                                       
                                     </xs:simpleType>
                                 </xs:element>
                                <xs:element name="Notes">
                                    <xs:complexType>
                                        <xs:all>
                                            <xs:element name="NoteNational"  type="TypeNote"></xs:element>
                                            <xs:element name="NoteRegional"  type="TypeNote"></xs:element>
                                        </xs:all>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="DateBac" type="xs:gYear"></xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
                <xs:attribute name="CNE" type="xs:NMTOKEN" use="required"></xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TypeEnseignant">
        <xs:complexContent>
            <xs:extension base="Person">
                <xs:sequence>
                    <xs:element name="Matiers">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="Matier" type="xs:string" maxOccurs="unbounded"></xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
                <xs:attribute type="xs:IDREFS" name="RefsEtablissment" use="required"></xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="TypeNote">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="10"></xs:minInclusive>
            <xs:maxInclusive value="20"></xs:maxInclusive>
            <xs:totalDigits value="4"></xs:totalDigits>
            <xs:fractionDigits value="2"></xs:fractionDigits>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Soufiane-Chajjaoui/XMLProject/DB-ESTS.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="StyleSheet-ESTS.xsl"?>

<Universite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="SCHEMA-ESTS.xsd"  idUniversite="CM1234"  UniversiteName="Cady ayyad">
    <Etablissments>
        <Etablissment idEtablissment="EST1" NomEtablissment="ECOLE Superieure de Technologie de SAFI" VileEtablissment="safi" RefUniversite="CM1234">
            <Etudiants>
                <Etudiant CNE="K133114870" idPerson="P1">
                    <Prenom>Soufiane</Prenom>
                    <Nom>Chajjaoui</Nom>
                    <Telephone>0720025322</Telephone>
                    <email>schajjaoui@gmail.com</email>
                    <address>N:42 Rue 19 okba bnou nafia,Safi </address>
                    <sex>Homme</sex>
                    <DateNaissance>2003-09-08</DateNaissance>
                    <Bac>
                        <SpecBac>BAC SCIENCES PHYSIQUES.</SpecBac>
                        <Notes>
                            <NoteNational>14.36</NoteNational>
                            <NoteRegional>12.46</NoteRegional>
                        </Notes>
                        <DateBac>2021</DateBac>
                    </Bac>
                </Etudiant>
            </Etudiants>
            <Departments>
                <Department idDepartment="Dep1">Genie Informatique</Department>
                <Department idDepartment="Dep2">Techneque instrumental de managment et quality</Department>
                <Department idDepartment="Dep3">Techneque de Managment</Department>
                <Department idDepartment="Dep4">Genie Industriel</Department>
            </Departments>
            <Enseignants>
                <Enseignant idPerson="P2" RefsEtablissment="EST1">
                    <Prenom>Jamal</Prenom>
                    <Nom>Bakkas</Nom>
                    <Telephone>0606060600</Telephone>
                    <email>schajjaoui@gmail.com</email>
                    <address>Safi, Centre vile 12</address>
                    <sex>Homme</sex>
                    <DateNaissance>1973-09-20</DateNaissance>
                    <Matiers>
                        <Matier>UML</Matier>
                        <Matier>Structure De Donnees</Matier>
                        <Matier>Development Web</Matier>
                    </Matiers>
                </Enseignant>
                <Enseignant idPerson="P3" RefsEtablissment="EST1">
                    <Prenom>Soufiane</Prenom>
                    <Nom>Elhourri</Nom>
                    <Telephone>0606060600</Telephone>
                    <email>schajjaoui@gmail.com</email>
                    <address>Safi, Lamia 12</address>
                    <sex>Homme</sex>
                    <DateNaissance>1992-09-20</DateNaissance>
                    <Matiers>
                        <Matier>Network Administration</Matier>
                        <Matier>Development Web</Matier>
                    </Matiers>
                </Enseignant>
                <Enseignant idPerson="P4" RefsEtablissment="EST1">
                    <Prenom>Khadija</Prenom>
                    <Nom>Arhid</Nom>
                    <Telephone>0606060600</Telephone>
                    <email>schajjaoui@gmail.com</email>
                    <address>Casablanca , roche noire</address>
                    <sex>Femme</sex>
                    <DateNaissance>1984-09-20</DateNaissance>
                    <Matiers>
                        <Matier>Systeme d'information</Matier>
                    </Matiers>
                </Enseignant>
                <Enseignant idPerson="P5" RefsEtablissment="EST1">
                    <Prenom>Illham</Prenom>
                    <Nom>Mounir</Nom>
                    <Telephone>0606060600</Telephone>
                    <email>schajjaoui@gmail.com</email>
                    <address>Safi , Lamia</address>
                    <sex>Femme</sex>
                    <DateNaissance>1973-09-20</DateNaissance>
                    <Matiers>
                        <Matier>Base de donnees Avance</Matier>
                        <Matier>DateWarehouse</Matier>
                        <Matier>AI</Matier>
                    </Matiers>
                </Enseignant>
            </Enseignants>
        </Etablissment>
        <Etablissment idEtablissment="EST2" NomEtablissment="ECOLE Superieure de Technologie de Essaouira" VileEtablissment="Essaouira" RefUniversite="CM1234">
            <Etudiants>
                <Etudiant CNE="K133114870" idPerson="P10">
                    <Prenom>Siham</Prenom>
                    <Nom>Driham</Nom>
                    <Telephone>0720025322</Telephone>
                    <email>schajjaoui@gmail.com</email>
                    <address>N:42 Rue 19 okba bnou nafia,Safi </address>
                    <sex>Homme</sex>
                    <DateNaissance>2003-09-08</DateNaissance>
                    <Bac>
                        <SpecBac>BAC SCIENCES PHYSIQUES.</SpecBac>
                        <Notes>
                            <NoteNational>14.36</NoteNational>
                            <NoteRegional>12.46</NoteRegional>
                        </Notes>
                        <DateBac>2021</DateBac>
                    </Bac>
                </Etudiant>
            </Etudiants>
            <Departments>
                <Department idDepartment="Dep1">Genie Informatique</Department>
                <Department idDepartment="Dep2">Techneque instrumental de managment et quality</Department>
                <Department idDepartment="Dep3">Techneque de Managment</Department>
                <Department idDepartment="Dep4">Energie Renevualabe</Department>
            </Departments>
            <Enseignants>
                <Enseignant idPerson="P6" RefsEtablissment="EST1">
                    <Prenom>Jamal</Prenom>
                    <Nom>Bakkas</Nom>
                    <Telephone>0606060600</Telephone>
                    <email>schajjaoui@gmail.com</email>
                    <address>Safi, Massira 12</address>
                    <sex>Homme</sex>
                    <DateNaissance>1973-09-20</DateNaissance>
                    <Matiers>
                        <Matier>UML</Matier>
                        <Matier>Structure De Donnees</Matier>
                        <Matier>Development Web</Matier>
                    </Matiers>
                </Enseignant>
                <Enseignant idPerson="P7" RefsEtablissment="EST1">
                    <Prenom>Soufiane</Prenom>
                    <Nom>Elhourri</Nom>
                    <Telephone>0606060600</Telephone>
                    <email>schajjaoui@gmail.com</email>
                    <address>Safi, Massira 12</address>
                    <sex>Homme</sex>
                    <DateNaissance>1992-09-20</DateNaissance>
                    <Matiers>
                        <Matier>Network Administration</Matier>
                        <Matier>Development Web</Matier>
                    </Matiers>
                </Enseignant>
                <Enseignant idPerson="P8" RefsEtablissment="EST1">
                    <Prenom>Khadija</Prenom>
                    <Nom>Arhid</Nom>
                    <Telephone>0606060600</Telephone>
                    <email>schajjaoui@gmail.com</email>
                    <address>Casablanca , roche noire</address>
                    <sex>Homme</sex>
                    <DateNaissance>1992-09-20</DateNaissance>
                    <Matiers>
                        <Matier>Network Administration</Matier>
                        <Matier>Development Web</Matier>
                    </Matiers>
                </Enseignant>
            </Enseignants>
        </Etablissment>
    </Etablissments>
</Universite>
